"""Delete income model

Revision ID: 1f4ec5161b31
Revises: 70729b5ce17c
Create Date: 2024-12-16 01:41:26.342960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f4ec5161b31'
down_revision = '70729b5ce17c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.drop_index('ix_income_added_at')
        batch_op.drop_index('ix_income_income_date')
        batch_op.drop_index('ix_income_source')
        batch_op.drop_index('ix_income_user_id')

    op.drop_table('income')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('income',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('source', sa.VARCHAR(length=128), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('income_date', sa.DATE(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=256), nullable=True),
    sa.Column('added_at', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.create_index('ix_income_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_income_source', ['source'], unique=False)
        batch_op.create_index('ix_income_income_date', ['income_date'], unique=False)
        batch_op.create_index('ix_income_added_at', ['added_at'], unique=False)

    # ### end Alembic commands ###
