"""Add Expense model

Revision ID: 63fcea14f3e3
Revises: 0fefaaeed688
Create Date: 2024-12-10 17:56:52.689700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63fcea14f3e3'
down_revision = '0fefaaeed688'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expense_added_at'), ['added_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_expense_date'), ['expense_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_user_id'))
        batch_op.drop_index(batch_op.f('ix_expense_title'))
        batch_op.drop_index(batch_op.f('ix_expense_expense_date'))
        batch_op.drop_index(batch_op.f('ix_expense_added_at'))

    op.drop_table('expense')
    # ### end Alembic commands ###
