"""Add Income model

Revision ID: 70729b5ce17c
Revises: 63fcea14f3e3
Create Date: 2024-12-15 18:42:20.819962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70729b5ce17c'
down_revision = '63fcea14f3e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('income',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('income_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_income_added_at'), ['added_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_income_income_date'), ['income_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_income_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_income_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_income_user_id'))
        batch_op.drop_index(batch_op.f('ix_income_source'))
        batch_op.drop_index(batch_op.f('ix_income_income_date'))
        batch_op.drop_index(batch_op.f('ix_income_added_at'))

    op.drop_table('income')
    # ### end Alembic commands ###
