"""Edit table name

Revision ID: 859d49fdaaa6
Revises: dd383ebc69ad
Create Date: 2024-12-07 22:35:06.799481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '859d49fdaaa6'
down_revision = 'dd383ebc69ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_stamp', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(length=140), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_time_stamp'), ['time_stamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_index('ix_expense_time_stamp')
        batch_op.drop_index('ix_expense_user_id')

    op.drop_table('expense')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('time_stamp', sa.DATETIME(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=140), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.create_index('ix_expense_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_expense_time_stamp', ['time_stamp'], unique=False)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_user_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_time_stamp'))

    op.drop_table('transaction')
    # ### end Alembic commands ###
